version: '3'

services:
  backend:
    build: ./toolbox-express
    ports:
      - '4000:4000'

  front:
    build: ./toolbox_react_redux
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on: 
      - backend


