version: '3'

services:
  backend:
    build: ./toolbox-express
    ports:
      - '4000:4000'
    networks:
     - toolbox-network

  front:
    build: ./toolbox-react-redux
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on: 
      - backend
    volumes:
      - ./toolbox-react-redux/src:/app/src  
    networks:
     - toolbox-network

networks:
    toolbox-network:
        driver: bridge



